#!/bin/bash
rm -rf CMakeCache.txt
rm -rf CMakeFiles
 
EXTRA_ARGS=$@
 
TRILINOS_HOME='/scratch/Trilinos_new/Trilinos'

INSTALL_DIR='/scratch/Trilinos_new/Trilinos/build_opt/install'
 
cmake \
-D Trilinos_ENABLE_Fortran=OFF \
-D CMAKE_BUILD_TYPE:STRING=RELEASE \
-D TPL_ENABLE_MPI:BOOL=ON \
-D CMAKE_CXX_FLAGS:STRING="-fPIC" \
-D BUILD_SHARED_LIBS:BOOL=OFF \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES:BOOL=ON \
-D Trilinos_ENABLE_ROL:BOOL=ON \
-D ROL_ENABLE_EXAMPLES:BOOL=ON \
-D CMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR} \
-D TPL_ENABLE_Boost=ON \
-D Boost_INCLUDE_DIRS=/projects/sems/install/rhel7-x86_64/sems/tpl/boost/1.63.0/gcc/6.1.0/base/include \
-D BoostLib_INCLUDE_DIRS=/projects/sems/install/rhel7-x86_64/sems/tpl/boost/1.63.0/gcc/6.1.0/base/include \
-D BoostLib_LIBRARY_DIRS=/projects/sems/install/rhel7-x86_64/sems/tpl/boost/1.63.0/gcc/6.1.0/base/lib \
-D TPL_BLAS_LIBRARIES:STRING=/usr/lib64/libblas.so \
-D TPL_LAPACK_LIBRARIES:STRING=/usr/lib64/liblapack.so \
$EXTRA_ARGS \
${TRILINOS_HOME}
