#!/bin/bash
rm -rf CMakeCache.txt
rm -rf CMakeFiles

EXTRA_ARGS=$@

# Machine type: Ubuntu 24.04.4 LTS
# Compiler: g++
 
rm CMakeCache.txt
rm -rf CMakeFiles/

TRILINOS_HOME="/path/to/Trilinos"
TRILINOS_INSTALL="/path/to/Trilinos/install"
HDSALIB_HOME="/path/to/HdsaLib"
OEDLIB_HOME="${HDSALIB_HOME}/OedLib"
MRHYDE_HOME="/path/to/MrHyDE"
MRHYDE_INSTALL="/path/to/MrHyDE/install"

cmake \
${MRHYDE_HOME} \
-GNinja \
-D Trilinos_SRC_DIR=${TRILINOS_HOME} \
-D Trilinos_INSTALL_DIR=${TRILINOS_INSTALL} \
-D OedLib_SRC_DIR=${OEDLIB_HOME} \
-D HdsaLib_SRC_DIR=${HDSALIB_HOME} \
-D CMAKE_INSTALL_PREFIX:PATH=${MRHYDE_INSTALL} \
-D CMAKE_CXX_FLAGS:STRING="-Wall" \
-D MrHyDE_ENABLE_SANDBOX=OFF \
-D MrHyDE_MAX_DERIVS=64 \
-D MrHyDE_BUILD_DOXYGEN=false \
-D MrHyDE_ENABLE_OED=ON \
${EXTRA-ARGS} \
