#ADD_SUBDIRECTORY(brandes_griesse)
#ADD_SUBDIRECTORY(darcy_flow)
#ADD_SUBDIRECTORY(darcy_adv_diff_dynamic_perm_inversion_regularization_update)
#ADD_SUBDIRECTORY(darcy_flow_LIS)
#ADD_SUBDIRECTORY(shallow_ice_velocity_state)
#ADD_SUBDIRECTORY(SSA_ice_model)
#ADD_SUBDIRECTORY(shallow_ice_bedrock_inv)
#ADD_SUBDIRECTORY(shallow_ice_bedrock_inv_small)
#ADD_SUBDIRECTORY(CDR_model_error_test)
#ADD_SUBDIRECTORY(synthetic_model_error_test)
#ADD_SUBDIRECTORY(CDR_control)
#ADD_SUBDIRECTORY(thermal-fluids)
#ADD_SUBDIRECTORY(Mass_and_Stiffness_Matrices)
ADD_SUBDIRECTORY(bayes_hdsa_model_error_test)
