#include "trilinos_adapter/core/HDSA_Ptr.hpp"
#include "trilinos_adapter/core/HDSA_Comm.hpp"
#include "trilinos_adapter/core/HDSA_ParameterList.hpp"
#include "trilinos_adapter/core/HDSA_Dense_Matrix.hpp"
#include "trilinos_adapter/core/HDSA_Stack_Trace.hpp"

#include "core/base/HDSA_Vector.hpp"
#include "core/base/HDSA_Linear_Operator.hpp"
#include "trilinos_adapter/adapters/HDSA_Belos_Adapter.hpp"
#include "trilinos_adapter/core/HDSA_Linear_Algebra.hpp"

#include "core/base/HDSA_Random_Number_Generator.hpp"
#include "core/base/HDSA_Std_Vector.hpp"
#include "core/base/HDSA_MultiVector.hpp"
#include "core/base/HDSA_Stream.hpp"
#include "core/base/HDSA_Randomized_GSVD.hpp"
#include "core/base/HDSA_Randomized_GEVP.hpp"
#include "core/base/HDSA_Operator_Sqrt.hpp"
#include "core/base/HDSA_Hessian_Inversion.hpp"

#include "core/model_discrepancy/interfaces/HDSA_MD_Data_Interface.hpp"
#include "core/model_discrepancy/interfaces/HDSA_MD_Opt_Prob_Interface.hpp"
#include "core/model_discrepancy/interfaces/HDSA_MD_u_Prior_Interface.hpp"
#include "core/model_discrepancy/interfaces/HDSA_MD_z_Prior_Interface.hpp"
#include "core/model_discrepancy/interfaces/HDSA_MD_Elliptic_u_Prior_Interface.hpp"
#include "core/model_discrepancy/interfaces/HDSA_MD_Elliptic_z_Prior_Interface.hpp"
#include "core/model_discrepancy/analysis/HDSA_MD_Prior_Sampling.hpp"
#include "core/model_discrepancy/analysis/HDSA_MD_Posterior_Vectors.hpp"
#include "core/model_discrepancy/analysis/HDSA_MD_Posterior_Data.hpp"
#include "core/model_discrepancy/analysis/HDSA_MD_Posterior_Sampling.hpp"
#include "core/model_discrepancy/analysis/HDSA_MD_Hessian_Analysis.hpp"
#include "core/model_discrepancy/analysis/HDSA_MD_Update.hpp"

#include "../interfaces/rol/HDSA_ROL_Vector.hpp"

#include "core/parametric_continuation/interfaces/HDSA_PC_Sensitivity_Operator_Interface.hpp"
#include "core/parametric_continuation/interfaces/HDSA_PC_LIS_Interface.hpp"
#include "core/parametric_continuation/analysis/HDSA_PC_Quasi_Newton_Preconditioner.hpp"
#include "core/parametric_continuation/analysis/HDSA_PC_Quasi_Newton_Preconditioner_LIS.hpp"
#include "core/parametric_continuation/analysis/HDSA_PC_Pseudo_Time_Continuation.hpp"

#include "../interfaces/rol/HDSA_ROL_Vector.hpp"
#include "../interfaces/rol/HDSA_MD_ROL_Opt_Prob_Interface.hpp"

//#include "../interfaces/mrhyde/Mrhyde_userInterface.hpp"
//#include "../interfaces/mrhyde/HDSA_Vector_Mrhyde.hpp"
//#include "../interfaces/mrhyde/HDSA_Mrhyde_State_Vector.hpp"
//#include "../interfaces/mrhyde/obj_mrhyde.hpp"
//#include "../interfaces/mrhyde/MD_Interface_Mrhyde.hpp"
//#include "../interfaces/mrhyde/Mrhyde_userInterface.hpp"
